

name: Next static build and export with HTML/JS minification


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  testtest:
    name: build on node ${{ matrix.node_version }} and ${{ matrix.node }}
    runs-on: ${{ matrix.node }}
    strategy:
      matrix:
        node_version: [ 14, 16, 18 ]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run:
        npm ci
        npm install
        npm run build --if-present

